config/routes.rb
Rails.application.routes.draw do
  resources :people
  get 'hello/world'
  post 'people/get_data'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parser.rb
class Parser
  def self.all
    ('A'..'Z').each do |char|
      parse_and_save(char)
    end
  end

  def self.parse_and_save(_name, _country='RUS')
    # example: dph_RegistryContent_SearchResults_ctl08_registryListItem -> dph_RegistryContent_SearchResults_ctl08_nameLabel1
    url = "https://certification.pmi.org/registry.aspx"
    form_id_selector = '_Form'
    lastname_id_selector = 'dph_RegistryContent_tbSearch'
    country_id_selector = 'dph_RegistryContent_wcountry'

    agent = Mechanize.new
    login_form = agent.get(url).form(form_id_selector)
    login_form.field_with(id: lastname_id_selector).value = _name
    login_form.field_with(id: country_id_selector).value = _country
    page = login_form.submit

    rows = page.search('#article table tr')
    rows.shift

    data = []

    rows.each do |row|
      tr_id = row.attributes['id'].value
      person = {}
      name, city, country, credential, earned, status = search_items(row, tr_id)
      person[:name] = name.present? ? name : data.last[:name]
      person[:city] = city.present? ? city : data.last[:city]
      person[:country] = country.present? ? country : data.last[:country]
      person[:credential] = credential.present? ? credential : data.last[:credential]
      person[:earned] = earned.present? ? earned : data.last[:earned]
      person[:status] = status.present? ? status : data.last[:status]
      data << person
    end

    Person.save_all(data)
  end

  def self.search_items(row, id)
    labels = ['nameLabel', 'cityStateLabel', 'countryLabel', 'certTypeLabel', 'certDateLabel', 'certStatusLabel']
    items = []
    labels.each do |label|
      items << row.search(get_id_selector(id, label)).text
    end
    items
  end

  def self.get_id_selector(id, label)
    tr_label = 'registryListItem'
    '#' + id.gsub(tr_label, label + '1')
  end

end

app/models/person.rb
class Person < ApplicationRecord
  def self.save_all(items)
    items.each { |item| Person.new(item).save! }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
    Parser.all
    @message = "Successful!"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_data
    Parser.all
    redirect_to :action => 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :city, :country, :credential, :earned, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/hello/world.html.erb
<h1>Hello#world</h1>

<p><%= @message %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :credential %>
    <%= form.text_field :credential %>
  </div>

  <div class="field">
    <%= form.label :earned %>
    <%= form.date_select :earned %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<%= button_to 'PARSE', {action: 'get_data', remote: true} %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Country</th>
      <th>Credential</th>
      <th>Earned</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.city %></td>
        <td><%= person.country %></td>
        <td><%= person.credential %></td>
        <td><%= person.earned %></td>
        <td><%= person.status %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @person.country %>
</p>

<p>
  <strong>Credential:</strong>
  <%= @person.credential %>
</p>

<p>
  <strong>Earned:</strong>
  <%= @person.earned %>
</p>

<p>
  <strong>Status:</strong>
  <%= @person.status %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>